name: Build DomoC nodes

on: [push, pull_request]

jobs:
  build-step:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build STEP node
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: release-v5.2
          target: esp32s3
          path: 'Code/nodes/step'
          command: 'idf.py set-target esp32s3 && idf.py build'
